{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $name, $value := .Values.configs }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
