{{- if .Values.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "api.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "api.name" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
{{- end }}
