{{- if .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "app.name" . }}-secret
  data:
  {{- range $v := .Values.secrets.data }}
  - secretKey: {{ $v.name }}
    remoteRef:
      key: {{ $.Values.secrets.key }}
      version: latest
      property: {{ $v.property }}
      {{- if $v.decodingStrategy }}
      decodingStrategy: {{ $v.decodingStrategy }}
      {{- end }}
  {{- end }}
{{- end }}
