version: '3.9'

services:
  app:
    container_name: dev-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - .env
    command: ["run", "dev"]
