name: Build and Deploy

on:
  push:
    branches:
      - release/production

jobs:
  build-and-deploy:
    name: Build docker image and deploy via ArgoCD
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ping-pong-repo/ping-pong:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ping-pong-repo/ping-pong:$IMAGE_TAG

    - name: Install yq
      run: sudo snap install yq

    - name: Update values.yaml with new image tag
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        yq e '.image.tag = strenv(IMAGE_TAG)' -i argocd/values.yaml

    - name: Commit and push updated values.yaml
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add argocd/values.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
